[package]
name = "gru-opengl-demo"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "desktop"
path = "src/main.rs"

[dependencies]
gru-opengl = { path = "../../gru-opengl" }
gru-math = { path = "../../gru-misc/gru-math" }
gru-text = { path = "../../gru-misc/gru-text" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.73"
[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.2.1"

[profile.release]
lto = true

# Android.xml, quite broken for some entries...

[package.metadata.android]
label = "opengl"
package_name = "gru.opengl.demo"

android_version = "26"
target_sdk_version = "26"
min_sdk_version = "18"

build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]

opengles_version_major = 2
opengles_version_minor = 0

fullscreen = true
orientation = "sensorLandscape"
installLocation = "preferExternal"

[package.metadata.android.application]
debuggable = false
theme = "@android:style/Theme.DeviceDefault.NoActionBar.Fullscreen"
#icon = "@mipmap/ic_launcher"
# res = "path/to/res_folder"
# assets = "path/to/assets_folder"

[package.metadata.android.application.activity]
config_changes = "orientation"
launch_mode = "singleTop"
#orientation = "landscape"
