[workspace]
members = ["gru-opengl-demo", "gru-wgpu-demo", "gru-vulkan-demo", "gru-script-demo", "gru-steam-demo"]
resolver = "3"

[profile.dev]
opt-level = 1

[profile.dev.package.'*']
opt-level = 3

[profile.release]
lto = "fat"
