[package]
name = "gru-vulkan-demo"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2021"

[dependencies]
gru-vulkan = { path = "../../gru-vulkan" }
gru-misc = { path = "../../gru-misc", features = ["math", "text_sdf", "time"] }
winit = "0.28.6"
